### ISSUE TITLE
some make error

### ISSUE THREAD

**Issue by jockcivil** [karfield/adb#1]
luosu@luosu-laptop:~/adb$ sudo make
make  all-recursive
make[1]: Entering directory `/home/luosu/adb'
Making all in libcutils
make[2]: Entering directory`/home/luosu/adb/libcutils'
source='socket_inaddr_any_server.c' object='libcutils_a-socket_inaddr_any_server.o' libtool=no \
    DEPDIR=.deps depmode=none /bin/bash ../depcomp \
    gcc -DHAVE_CONFIG_H -I. -I.. -I../include   -O2 -g -Wall -DANDROID_SMP=0 -DLIBC_STATIC -DDLMALLOC_DEBUG -DHAVE_PTHREADS -DHOST_OS=linux -g -O2 -c -o libcutils_a-socket_inaddr_any_server.o `test -f 'socket_inaddr_any_server.c' || echo './'`socket_inaddr_any_server.c
/usr/local/share/automake-1.11/depcomp: No command.  Try '/usr/local/share/automake-1.11/depcomp --help' for more information.
make[2]: **\* [libcutils_a-socket_inaddr_any_server.o] Error 1
make[2]: Leaving directory `/home/luosu/adb/libcutils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/luosu/adb'
make: **\* [all] Error 2
luosu@luosu-laptop:~/adb$

**Comment by karfield** [comment]
I think you may not have installed automake stuff, you could try 'apt-get install automake build-essential' if using debian/ubuntu.

**Comment by jockcivil** [comment]
I have installed automake tools.

---

russell@russell-laptop:~/adb$ make
 cd . && /bin/bash ./config.status Makefile 
./config.status: line 530: config.log: Permission denied
make: **\* [Makefile] Error 1
russell@russell-laptop:~/adb$ sudo make
[sudo] password for russell: 
 cd . && /bin/bash ./config.status Makefile 
config.status: creating Makefile
make  all-recursive
make[1]: Entering directory `/home/russell/adb'
Making all in libcutils
make[2]: Entering directory`/home/russell/adb/libcutils'
 cd .. && /bin/bash ./config.status libcutils/Makefile depfiles
config.status: creating libcutils/Makefile
config.status: executing depfiles commands
make[2]: Leaving directory `/home/russell/adb/libcutils'
make[2]: Entering directory`/home/russell/adb/libcutils'
source='socket_inaddr_any_server.c' object='libcutils_a-socket_inaddr_any_server.o' libtool=no \
    DEPDIR=.deps depmode=none /bin/bash ../depcomp \
    gcc -DHAVE_CONFIG_H -I. -I.. -I../include   -O2 -g -Wall -DANDROID_SMP=0 -DLIBC_STATIC -DDLMALLOC_DEBUG -DHAVE_PTHREADS -DHOST_OS=linux -g -O2 -c -o libcutils_a-socket_inaddr_any_server.o `test -f 'socket_inaddr_any_server.c' || echo './'`socket_inaddr_any_server.c
/usr/share/automake-1.11/depcomp: No command.  Try `/usr/share/automake-1.11/depcomp --help' for more information.
make[2]: *** [libcutils_a-socket_inaddr_any_server.o] Error 1
make[2]: Leaving directory`/home/russell/adb/libcutils'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/russell/adb'
make: **\* [all] Error 2

russell@russell-laptop:~/adb$ /usr/share/automake-1.11/depcomp --help
Usage: depcomp [--help] [--version] PROGRAM [ARGS]

Run PROGRAMS ARGS to compile a file, generating dependencies
as side-effects.
Environment variables:
  depmode     Dependency tracking mode.
  source      Source file read by `PROGRAMS ARGS'.
  object      Object file output by`PROGRAMS ARGS'.
  DEPDIR      directory where to store dependencies.
  depfile     Dependency file to output.
  tmpdepfile  Temporary file to use when outputing dependencies.
  libtool     Whether libtool is used (yes/no).

Report bugs to bug-automake@gnu.org.
russell@russell-laptop:~/adb$

**Comment by karfield** [comment]
You could try ./autogen.sh and ./configure again to re-link the automake utils. I used the old debian(squeeze 6) to generate the Makefile, so the automake utils may be different from yours.
