### ISSUE TITLE
make adb available for freebsd users

### ISSUE THREAD

**Issue by rosorio** [karfield/adb#2]
Hi,

I start madding changes to make your project available for FreeBSD users. Currently only abd runs without problem on FreeBSD ; I left fastboot for later.
If you are interested by my changes don't hesitate to pick them all from my forked repo.

best regards
- rodrigo

**Comment by karfield** [comment]
Hi Rosorio,

Thank you so much! (I've been a long time to check this repo, it's my fault to delay to close this issue.)

Can you create a pull request for me? So I can merge your branch to my repo.

Best regards.
